// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebTemplate.Models;

#nullable disable

namespace WebTemplate.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20231215120814_V1")]
    partial class V1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebTemplate.Models.Elektrodistribucija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<long>("BrojRadnika")
                        .HasColumnType("bigint");

                    b.Property<string>("Gmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Elektrodistribucije");
                });

            modelBuilder.Entity("WebTemplate.Models.Potrosac", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<long>("GodinaRodjenja")
                        .HasColumnType("bigint");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MestoRodjenja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Potrosaci");
                });

            modelBuilder.Entity("WebTemplate.Models.Potrosnja", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BrojBrojila")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumUgovora")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ElektrodistribucijaID")
                        .HasColumnType("int");

                    b.Property<long>("KorisnickiBroj")
                        .HasColumnType("bigint");

                    b.Property<int?>("PotrosacID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ElektrodistribucijaID");

                    b.HasIndex("PotrosacID");

                    b.ToTable("Potrosnje");
                });

            modelBuilder.Entity("WebTemplate.Models.Potrosnja", b =>
                {
                    b.HasOne("WebTemplate.Models.Elektrodistribucija", "Elektrodistribucija")
                        .WithMany("Potrosnje")
                        .HasForeignKey("ElektrodistribucijaID");

                    b.HasOne("WebTemplate.Models.Potrosac", "Potrosac")
                        .WithMany("Potrosnje")
                        .HasForeignKey("PotrosacID");

                    b.Navigation("Elektrodistribucija");

                    b.Navigation("Potrosac");
                });

            modelBuilder.Entity("WebTemplate.Models.Elektrodistribucija", b =>
                {
                    b.Navigation("Potrosnje");
                });

            modelBuilder.Entity("WebTemplate.Models.Potrosac", b =>
                {
                    b.Navigation("Potrosnje");
                });
#pragma warning restore 612, 618
        }
    }
}
